import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import {Button, Flex, Box} from '@chakra-ui/react'
import { useState } from 'react'

export default function Home() {
  const [favicon,setFavicon] = useState('')
  const [title, setTitle] = useState('')
  const handleClick = () => {
    setFavicon('Like')
    setTitle('Like!')
    setTimeout(() => {
      setFavicon('')
      setTitle('')
    },3000)
  }
  return (
    <div className={styles.container}>
      <Head>
        <title>{title ? `${title}` : "Aplicación Favicon"} </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href={favicon ? `/heart-${favicon}.png` : `/favicon-16x16.png` } />
      </Head>
      <Flex justify={'center'} w={'100%'} direction={'column'}>
          <Box alignSelf={'center'}>Clic si te gusto el video</Box>
          <Box alignSelf={'center'} my={5}>
            <Button onClick={handleClick}>Like</Button>
          </Box>
      </Flex>
    </div>
  )
}
